<?php

return [
    'APIMS_USERNAME' => env('APIMS_USERNAME'),
    'APIMS_PASSWORD' => env('APIMS_PASSWORD'),
    'APIMS_ENDPOINT' => env('APIMS_ENDPOINT'),
    'APIMS_PRIVATE_KEY_PATH' => env('APIMS_PRIVATE_KEY_PATH'),

];